export const sampleRecipes = [
  {
    name: "Aloo Jeera with Phulka & Salad",
    description: "Classic Indian dry spiced potatoes tempered with roasted cumin seeds and fresh coriander, served with warm phulkas.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 10,
    cookTime: 15,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 340, protein: 8, carbs: 58, fat: 9, fiber: 6 },
    dietaryFlags: ["vegetarian", "vegan", "quick-meal", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=700&auto=format&fit=crop&q=80",
    tags: ["everyday", "quick", "comfort food", "no onion garlic option"],
    defaultDecisionTip: "Fastest wholesome dinner under 25 mins using simple kitchen pantry staples.",
    ingredients: [
      { name: "Potato", quantity: 3, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Cumin Seeds (Jeera)", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Green Chilli", quantity: 2, unit: "pieces", isPantryStaple: false, category: "Vegetables" },
      { name: "Turmeric Powder", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Coriander Powder", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Mustard Oil / Cooking Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Fresh Coriander", quantity: 2, unit: "tbsp", isPantryStaple: false, category: "Vegetables" },
      { name: "Whole Wheat Flour (Atta)", quantity: 1.5, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Salt", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" }
    ],
    instructions: [
      "Boil and peel the potatoes, then dice into bite-sized cubes.",
      "Heat mustard oil in a kadai until smoking hot, reduce flame and add cumin seeds and slit green chillies.",
      "Add diced potatoes, turmeric, coriander powder, amchur (dry mango powder), and salt.",
      "Sauté on medium-high flame for 6-8 minutes until crisp and golden brown on edges.",
      "Knead wheat flour with warm water into a soft dough and roll out round phulkas/rotis on a hot tawa.",
      "Garnish potatoes with fresh chopped coriander and serve hot with fresh puffed rotis."
    ]
  },
  {
    name: "Dal Tadka with Steamed Basmati Rice & Papad",
    description: "Yellow toor & moong lentils simmered to creamy perfection and tempered with ghee, garlic, hing, and Kashmiri red chillies.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 10,
    cookTime: 20,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 420, protein: 18, carbs: 70, fat: 8, fiber: 9 },
    dietaryFlags: ["vegetarian", "gluten-free", "high-protein", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=700&auto=format&fit=crop&q=80",
    tags: ["comfort", "protein rich", "staple", "soothing"],
    defaultDecisionTip: "Ultimate Indian soul food that balances proteins, fiber, and soothing comfort.",
    ingredients: [
      { name: "Toor Dal (Pigeon Pea)", quantity: 0.75, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Moong Dal", quantity: 0.25, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Onion", quantity: 1, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 1, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Garlic", quantity: 5, unit: "cloves", isPantryStaple: false, category: "Vegetables" },
      { name: "Ginger", quantity: 1, unit: "inch", isPantryStaple: false, category: "Vegetables" },
      { name: "Ghee", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Basmati Rice", quantity: 1, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Dry Red Chilli", quantity: 2, unit: "pieces", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Asafoetida (Hing)", quantity: 1, unit: "pinch", isPantryStaple: true, category: "Spices & Condiments" }
    ],
    instructions: [
      "Wash toor and moong dal thoroughly and pressure cook with water, turmeric, and salt for 3-4 whistles.",
      "Cook basmati rice with double volume of water in a separate pot until fluffy.",
      "Heat ghee in a pan, add cumin seeds, hing, dry red chillies, and finely chopped garlic until aromatic and golden.",
      "Add chopped onions and ginger; sauté until translucent, followed by chopped tomatoes until soft.",
      "Pour cooked dal into the tempering, adjust consistency with water, and simmer for 3 minutes.",
      "Serve piping hot over fragrant steamed rice with roasted papad."
    ]
  },
  {
    name: "Paneer Bhurji with Butter Toast / Paratha",
    description: "Scrambled cottage cheese tossed with sautéed onions, tomatoes, capsicum, and aromatic pav bhaji spices.",
    mealType: ["breakfast", "dinner"],
    cuisine: "North Indian",
    prepTime: 8,
    cookTime: 12,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 460, protein: 24, carbs: 28, fat: 28, fiber: 4 },
    dietaryFlags: ["vegetarian", "high-protein", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=700&auto=format&fit=crop&q=80",
    tags: ["high protein", "quick dinner", "bachelor friendly", "paneer"],
    defaultDecisionTip: "Takes just 20 mins total with a huge 24g protein boost per serving.",
    ingredients: [
      { name: "Paneer (Cottage Cheese)", quantity: 200, unit: "grams", isPantryStaple: false, category: "Dairy" },
      { name: "Onion", quantity: 2, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 1, unit: "large", isPantryStaple: false, category: "Vegetables" },
      { name: "Capsicum (Bell Pepper)", quantity: 0.5, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli", quantity: 2, unit: "pieces", isPantryStaple: false, category: "Vegetables" },
      { name: "Butter / Ghee", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Pav Bhaji Masala / Garam Masala", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Kasuri Methi", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Whole Wheat Bread / Paratha", quantity: 4, unit: "slices", isPantryStaple: false, category: "Bakery" }
    ],
    instructions: [
      "Crumble fresh paneer by hand and set aside.",
      "Heat butter in a skillet, add cumin seeds, finely chopped onions, and green chillies. Sauté until lightly browned.",
      "Add diced tomatoes and diced capsicum with turmeric, chilli powder, pav bhaji masala, and salt. Cook until mushy.",
      "Fold in crumbled paneer and crushed kasuri methi on medium heat. Sauté for only 2-3 minutes to keep paneer soft.",
      "Toast bread or paratha with butter on a hot pan.",
      "Serve warm garnished with lemon wedge and fresh coriander."
    ]
  },
  {
    name: "Kanda Poha with Roasted Peanuts & Lemon",
    description: "Fluffy flattened rice flakes tempered with mustard seeds, curry leaves, onions, turmeric, and crunchy roasted peanuts.",
    mealType: ["breakfast", "snack"],
    cuisine: "Maharashtrian",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 290, protein: 7, carbs: 52, fat: 7, fiber: 4 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "quick-meal", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=700&auto=format&fit=crop&q=80",
    tags: ["breakfast classic", "super quick", "light", "gluten free"],
    defaultDecisionTip: "Ready in 15 minutes flat; ultra light on the stomach and refreshing.",
    ingredients: [
      { name: "Thick Poha (Flattened Rice)", quantity: 2, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Onion", quantity: 1, unit: "large", isPantryStaple: false, category: "Vegetables" },
      { name: "Raw Peanuts", quantity: 3, unit: "tbsp", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Mustard Seeds (Rai)", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Curry Leaves", quantity: 8, unit: "leaves", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli", quantity: 2, unit: "pieces", isPantryStaple: false, category: "Vegetables" },
      { name: "Turmeric Powder", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Lemon", quantity: 0.5, unit: "piece", isPantryStaple: false, category: "Vegetables" },
      { name: "Oil", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" }
    ],
    instructions: [
      "Rinse poha in a colander under running water for 30 seconds and drain completely. Sprinkle salt and a pinch of sugar.",
      "Heat oil in a pan, fry peanuts until golden brown and crispy; keep aside or push to side.",
      "In the same oil, add mustard seeds, curry leaves, slit green chillies, and finely chopped onions.",
      "Sauté onions until translucent and pink, add turmeric powder.",
      "Add drained poha and roasted peanuts. Gently toss on low flame for 2-3 minutes with lid on.",
      "Turn off flame, squeeze fresh lemon juice, garnish with coriander and sev if desired, and enjoy with hot chai."
    ]
  },
  {
    name: "Rajma Masala with Steamed Jeera Rice",
    description: "Velvety kidney beans slow-cooked in a rich, spiced onion-tomato gravy infused with ginger and Punjabi spices.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 15,
    cookTime: 35,
    difficulty: "Medium",
    servingSize: 4,
    nutrition: { calories: 480, protein: 19, carbs: 78, fat: 10, fiber: 13 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "high-protein", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=700&auto=format&fit=crop&q=80",
    tags: ["sunday special", "family favorite", "hearty", "high protein"],
    defaultDecisionTip: "Hearty weekend favorite that delivers a complete protein meal loved by the entire family.",
    ingredients: [
      { name: "Rajma (Red Kidney Beans)", quantity: 1.5, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Onion", quantity: 2, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato Puree", quantity: 1, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Ginger Garlic Paste", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Rajma Masala / Garam Masala", quantity: 1.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Kashmiri Red Chilli Powder", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Ghee / Mustard Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Basmati Rice", quantity: 2, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Cumin Seeds", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" }
    ],
    instructions: [
      "Soak rajma overnight or for 6 hours. Pressure cook with whole spices and salt for 6-7 whistles until melt-in-mouth soft.",
      "In a deep kadai, heat ghee/oil, add cumin seeds and finely minced onions. Brown onions deeply for rich flavor.",
      "Add ginger-garlic paste and sauté until raw smell disappears.",
      "Add tomato puree, turmeric, red chilli powder, coriander powder, and rajma masala. Cook until oil separates.",
      "Add cooked rajma along with its broth. Mash a few beans with the back of a ladle to thicken gravy naturally.",
      "Simmer on low flame for 15-20 minutes. Serve hot with fragrant jeera rice and sliced onions."
    ]
  },
  {
    name: "Masala Egg Bhurji with Crispy Paratha",
    description: "Mumbai street-style spicy scrambled eggs cooked with chopped onions, tomatoes, green chillies, and fresh coriander.",
    mealType: ["breakfast", "dinner"],
    cuisine: "North Indian",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 410, protein: 22, carbs: 32, fat: 21, fiber: 3 },
    dietaryFlags: ["non-vegetarian", "eggetarian", "high-protein", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=700&auto=format&fit=crop&q=80",
    tags: ["quick protein", "bachelor hero", "under 15 mins", "street food"],
    defaultDecisionTip: "Fastest dinner when tired after work; requires almost zero prep and packs 22g quality protein.",
    ingredients: [
      { name: "Eggs", quantity: 4, unit: "large", isPantryStaple: false, category: "Meat & Seafood" },
      { name: "Onion", quantity: 1, unit: "large", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 1, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli", quantity: 2, unit: "pieces", isPantryStaple: false, category: "Vegetables" },
      { name: "Butter / Oil", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Pav Bhaji Masala / Kitchen King", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Turmeric Powder", quantity: 0.25, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Whole Wheat Paratha / Pav", quantity: 2, unit: "pieces", isPantryStaple: false, category: "Bakery" }
    ],
    instructions: [
      "Whisk eggs in a bowl with salt and a splash of milk.",
      "Heat butter/oil in a pan, sauté finely chopped onions and green chillies until golden.",
      "Add chopped tomatoes, turmeric, and pav bhaji masala; cook for 2 minutes until tomatoes turn soft.",
      "Pour in beaten eggs and scramble gently on medium heat until soft and moist.",
      "Do not overcook to keep bhurji succulent. Garnish with chopped coriander.",
      "Serve hot with toasted buttered pav or flaky parathas."
    ]
  },
  {
    name: "Moong Dal Khichdi with Ghee, Kadhi & Papad",
    description: "Soothing one-pot wholesome blend of rice and yellow moong lentils tempered with hing and cumin, paired with Gujarati kadhi.",
    mealType: ["lunch", "dinner"],
    cuisine: "Gujarati",
    prepTime: 5,
    cookTime: 15,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 360, protein: 14, carbs: 62, fat: 7, fiber: 7 },
    dietaryFlags: ["vegetarian", "gluten-free", "healthy", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=700&auto=format&fit=crop&q=80",
    tags: ["comfort dinner", "one pot", "easy digest", "rainy day comfort"],
    defaultDecisionTip: "The ultimate restorative one-pot dinner when you want something light, warm, and effortless.",
    ingredients: [
      { name: "Yellow Moong Dal", quantity: 0.5, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Rice", quantity: 0.5, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Desi Ghee", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Cumin Seeds (Jeera)", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Asafoetida (Hing)", quantity: 1, unit: "pinch", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Black Peppercorns", quantity: 4, unit: "pieces", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Turmeric Powder", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Ginger", quantity: 0.5, unit: "inch", isPantryStaple: false, category: "Vegetables" }
    ],
    instructions: [
      "Wash rice and moong dal together and soak in water for 15 minutes.",
      "In a pressure cooker, heat 1 tbsp ghee, add cumin seeds, hing, black peppercorns, and grated ginger.",
      "Add drained rice-dal mix, turmeric, salt, and 3.5 cups of water.",
      "Pressure cook for 3-4 whistles on medium flame until soft and porridge-like consistency.",
      "Drizzle remaining hot desi ghee on top before serving with curd/kadhi, mango pickle, and roasted papad."
    ]
  },
  {
    name: "Crispy Masala Dosa with Coconut Chutney & Sambar",
    description: "Golden crispy fermented rice-lentil crepe filled with spiced tempered potato masala, served with fresh coconut chutney.",
    mealType: ["breakfast", "dinner"],
    cuisine: "South Indian",
    prepTime: 10,
    cookTime: 15,
    difficulty: "Medium",
    servingSize: 2,
    nutrition: { calories: 390, protein: 10, carbs: 64, fat: 11, fiber: 6 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free"],
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=700&auto=format&fit=crop&q=80",
    tags: ["south indian", "crispy", "restaurant style at home", "weekend"],
    defaultDecisionTip: "Classic South Indian comfort; quick if using ready batter or homemade fermented batter.",
    ingredients: [
      { name: "Dosa Batter", quantity: 2, unit: "cups", isPantryStaple: false, category: "Grains & Pulses" },
      { name: "Potato", quantity: 3, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Onion", quantity: 1, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Mustard Seeds", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Curry Leaves", quantity: 8, unit: "leaves", isPantryStaple: false, category: "Vegetables" },
      { name: "Fresh Grated Coconut", quantity: 0.5, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Ghee / Butter", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Dairy" }
    ],
    instructions: [
      "Boil and roughly mash potatoes. Temper mustard seeds, curry leaves, green chillies, sliced onions, and turmeric in oil.",
      "Add mashed potatoes with a splash of water and salt; simmer for 3 minutes for aloo masala.",
      "Blend grated coconut, green chilli, roasted chana dal, and salt into smooth chutney with mustard tadka.",
      "Heat a cast iron tawa, pour a ladle of batter, swirl thinly in circular motion.",
      "Drizzle ghee around edges, roast until golden brown and crispy, place potato filling in center, and fold.",
      "Serve piping hot with fresh coconut chutney and spicy sambar."
    ]
  },
  {
    name: "Paneer Butter Masala with Garlic Naan",
    description: "Soft paneer cubes simmered in a creamy, velvety makhani gravy enriched with butter, cashews, and aromatic kasuri methi.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Medium",
    servingSize: 3,
    nutrition: { calories: 540, protein: 20, carbs: 36, fat: 38, fiber: 5 },
    dietaryFlags: ["vegetarian", "high-protein"],
    imageUrl: "https://images.unsplash.com/photo-1631452180519-c014fe946bc7?w=700&auto=format&fit=crop&q=80",
    tags: ["indulgent", "restaurant style", "family dinner", "creamy"],
    defaultDecisionTip: "Rich restaurant-style treat for special family dinners or weekend indulgences.",
    ingredients: [
      { name: "Paneer", quantity: 250, unit: "grams", isPantryStaple: false, category: "Dairy" },
      { name: "Tomato Puree", quantity: 1.5, unit: "cups", isPantryStaple: false, category: "Vegetables" },
      { name: "Cashews", quantity: 12, unit: "pieces", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Butter", quantity: 3, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Fresh Cream", quantity: 2, unit: "tbsp", isPantryStaple: false, category: "Dairy" },
      { name: "Kashmiri Red Chilli Powder", quantity: 1.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Garam Masala", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Kasuri Methi", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Garlic Naan / Roti", quantity: 3, unit: "pieces", isPantryStaple: false, category: "Bakery" }
    ],
    instructions: [
      "Soak cashews in warm water for 15 mins and blend with tomato puree into a super silky paste.",
      "Melt 2 tbsp butter in a pan with whole spices (cardamom, cinnamon, bay leaf).",
      "Add ginger-garlic paste and sauté, followed by cashew-tomato paste, chilli powder, and salt.",
      "Cook on medium heat until the makhani gravy turns glossy and leaves the pan sides.",
      "Add warm water to adjust gravy consistency, then gently slide in fresh paneer cubes.",
      "Finish with fresh cream, crushed kasuri methi, and remaining butter. Serve with garlic naan."
    ]
  },
  {
    name: "Classic Egg Curry with Steamed Rice",
    description: "Boiled eggs shallow fried till blistered and simmered in a rustic, flavorful onion-tomato-garlic gravy.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 10,
    cookTime: 20,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 430, protein: 21, carbs: 48, fat: 18, fiber: 4 },
    dietaryFlags: ["non-vegetarian", "eggetarian", "high-protein", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1596797038530-2c107229654b?w=700&auto=format&fit=crop&q=80",
    tags: ["high protein", "everyday curry"],
    defaultDecisionTip: "Satisfying high-protein curry that pleases hearty appetites.",
    ingredients: [
      { name: "Eggs", quantity: 4, unit: "large", isPantryStaple: false, category: "Meat & Seafood" },
      { name: "Onion", quantity: 2, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 2, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Ginger Garlic Paste", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Turmeric Powder", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Coriander Powder", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Mustard Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Rice", quantity: 1, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" }
    ],
    instructions: [
      "Hard boil eggs, peel, make slight slits, and prick lightly with a fork.",
      "Heat 1 tbsp oil with a pinch of turmeric and chilli powder; shallow fry eggs until golden and blistered.",
      "In the remaining oil, sauté chopped onions until deep golden brown, then add ginger-garlic paste.",
      "Add pureed tomatoes and spices; sauté until oil separates from the masala.",
      "Add 1 cup water, bring to a boil, drop in the fried eggs, and simmer for 6-8 minutes.",
      "Garnish with chopped cilantro and serve with hot steamed rice."
    ]
  },
  {
    name: "Palak Paneer with Butter Roti",
    description: "Wholesome blanched spinach gravy infused with garlic, cumin, and mild spices, loaded with soft paneer cubes.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 12,
    cookTime: 18,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 380, protein: 22, carbs: 24, fat: 22, fiber: 8 },
    dietaryFlags: ["vegetarian", "gluten-free", "high-protein", "healthy", "low-calorie"],
    imageUrl: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=700&auto=format&fit=crop&q=80",
    tags: ["healthy greens", "iron rich", "high protein", "low calorie"],
    defaultDecisionTip: "Packed with iron and protein, keeping calorie count low while tasting rich and creamy.",
    ingredients: [
      { name: "Fresh Spinach (Palak)", quantity: 1, unit: "large bunch (300g)", isPantryStaple: false, category: "Vegetables" },
      { name: "Paneer", quantity: 200, unit: "grams", isPantryStaple: false, category: "Dairy" },
      { name: "Garlic", quantity: 6, unit: "cloves", isPantryStaple: false, category: "Vegetables" },
      { name: "Onion", quantity: 1, unit: "small", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli", quantity: 2, unit: "pieces", isPantryStaple: false, category: "Vegetables" },
      { name: "Ghee / Butter", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Garam Masala", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Fresh Cream", quantity: 1, unit: "tbsp", isPantryStaple: false, category: "Dairy" }
    ],
    instructions: [
      "Blanch spinach leaves in boiling water for 2 minutes, then immediately transfer to ice-cold water to retain bright green color.",
      "Puree the blanched spinach with green chillies into a silky smooth puree.",
      "Heat ghee in a pan, add cumin and plenty of minced garlic; sauté until aromatic.",
      "Add finely chopped onions and cook until translucent. Add spinach puree and salt.",
      "Simmer for 3-4 minutes on medium heat. Drop in cubed paneer and garam masala.",
      "Finish with a swirl of fresh cream and serve with warm rotis."
    ]
  },
  {
    name: "Veg Hakka Noodles with Stir-Fried Veggies",
    description: "Street-style Indo-Chinese noodles tossed with crunchy shredded cabbage, capsicum, carrots, garlic, and soy-chilli sauces.",
    mealType: ["dinner", "lunch"],
    cuisine: "Indo-Chinese",
    prepTime: 10,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 410, protein: 9, carbs: 68, fat: 12, fiber: 5 },
    dietaryFlags: ["vegetarian", "vegan", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=700&auto=format&fit=crop&q=80",
    tags: ["indo-chinese", "quick dinner", "kids favorite", "street style"],
    defaultDecisionTip: "Fast 20-minute Friday night favorite when craving Indo-Chinese takeout flavors.",
    ingredients: [
      { name: "Hakka Noodles", quantity: 200, unit: "grams", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Cabbage", quantity: 1, unit: "cup shredded", isPantryStaple: false, category: "Vegetables" },
      { name: "Capsicum", quantity: 1, unit: "sliced", isPantryStaple: false, category: "Vegetables" },
      { name: "Carrot", quantity: 1, unit: "julienned", isPantryStaple: false, category: "Vegetables" },
      { name: "Garlic", quantity: 5, unit: "cloves finely minced", isPantryStaple: false, category: "Vegetables" },
      { name: "Soy Sauce", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Green Chilli Sauce / Vinegar", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Black Pepper", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Cooking Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" }
    ],
    instructions: [
      "Boil noodles al dente in salted water, drain and toss with 1 tsp oil to prevent sticking.",
      "Heat oil in a large wok on high heat until smoking hot.",
      "Add minced garlic and sliced onions; stir-fry for 30 seconds.",
      "Add shredded carrots, capsicum, and cabbage. Stir-fry on high flame for 2 minutes to keep them crunchy.",
      "Add boiled noodles, soy sauce, chilli sauce, vinegar, black pepper, and salt.",
      "Toss vigorously on high flame for 2 minutes and serve steaming hot with spring onion garnish."
    ]
  },
  {
    name: "Classic Pav Bhaji with Butter Toasted Pav",
    description: "Mashed spiced medley of potatoes, cauliflower, peas, and capsicum cooked in rich butter on a large tawa.",
    mealType: ["dinner", "snack"],
    cuisine: "Maharashtrian",
    prepTime: 15,
    cookTime: 20,
    difficulty: "Medium",
    servingSize: 3,
    nutrition: { calories: 490, protein: 11, carbs: 72, fat: 18, fiber: 9 },
    dietaryFlags: ["vegetarian"],
    imageUrl: "https://images.unsplash.com/photo-1606491956689-2ea866880c84?w=700&auto=format&fit=crop&q=80",
    tags: ["street food", "weekend special", "mumbai special", "crowd pleaser"],
    defaultDecisionTip: "Perfect weekend crowd-pleaser that cleverly uses up mixed leftover vegetables in the fridge.",
    ingredients: [
      { name: "Potato", quantity: 3, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Peas (Matar)", quantity: 0.5, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Cauliflower", quantity: 1, unit: "cup florets", isPantryStaple: false, category: "Vegetables" },
      { name: "Capsicum", quantity: 1, unit: "finely diced", isPantryStaple: false, category: "Vegetables" },
      { name: "Onion", quantity: 2, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 3, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Pav Bhaji Masala", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Butter (Amul)", quantity: 4, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Pav Buns", quantity: 6, unit: "pieces", isPantryStaple: false, category: "Bakery" }
    ],
    instructions: [
      "Pressure cook potatoes, cauliflower, and green peas with water for 3 whistles. Mash thoroughly with a potato masher.",
      "In a wide pan/tawa, heat 2 tbsp butter, sauté onions and capsicum until soft.",
      "Add ginger-garlic paste and tomatoes; cook until mushy and butter starts releasing.",
      "Add pav bhaji masala, red chilli powder, and salt. Cook the masala base for 3 minutes.",
      "Add the mashed vegetables with 1/2 cup water. Mash continuously with the masher on simmer for 10 minutes until silky.",
      "Toast pav buns with butter and coriander on a hot tawa. Serve bhaji topped with a big dollop of butter, chopped onions, and lemon."
    ]
  },
  {
    name: "Healthy Besan Chilla with Mint Chutney",
    description: "Protein-rich savory gram flour pancakes loaded with finely chopped onions, tomatoes, ajwain, and green chillies.",
    mealType: ["breakfast", "snack"],
    cuisine: "North Indian",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 240, protein: 14, carbs: 32, fat: 6, fiber: 7 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "high-protein", "quick-meal", "healthy", "low-calorie"],
    imageUrl: "https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=700&auto=format&fit=crop&q=80",
    tags: ["weight loss", "instant", "high fiber", "diabetes friendly"],
    defaultDecisionTip: "Instant 15-minute breakfast with 14g plant protein and zero fermentation needed.",
    ingredients: [
      { name: "Besan (Gram Flour)", quantity: 1.5, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Onion", quantity: 1, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 1, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli", quantity: 2, unit: "minced", isPantryStaple: false, category: "Vegetables" },
      { name: "Ajwain (Carom Seeds)", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Turmeric Powder", quantity: 0.25, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Fresh Coriander", quantity: 2, unit: "tbsp", isPantryStaple: false, category: "Vegetables" },
      { name: "Oil", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" }
    ],
    instructions: [
      "In a mixing bowl, combine besan, ajwain, turmeric, chopped onions, tomatoes, green chillies, coriander, and salt.",
      "Gradually add water and whisk into a smooth, lump-free pouring consistency batter.",
      "Heat a non-stick tawa, drizzle a few drops of oil, and spread a ladle of batter into a thin round circle.",
      "Cook on medium flame until edges crisp up; flip and cook the other side for 1-2 minutes until golden brown spots appear.",
      "Serve warm with spicy green mint chutney or tomato ketchup."
    ]
  },
  {
    name: "Hyderabadi Vegetable Dum Biryani with Raita",
    description: "Fragrant basmati rice layered with spiced marinated vegetables, saffron milk, fried onions (birista), and slow cooked on dum.",
    mealType: ["lunch", "dinner"],
    cuisine: "Hyderabadi",
    prepTime: 20,
    cookTime: 30,
    difficulty: "Hard",
    servingSize: 4,
    nutrition: { calories: 450, protein: 12, carbs: 74, fat: 12, fiber: 7 },
    dietaryFlags: ["vegetarian", "gluten-free", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=700&auto=format&fit=crop&q=80",
    tags: ["festive", "royal", "fragrant", "weekend special"],
    defaultDecisionTip: "A royal feast in one pot when cooking for family gatherings or Sunday celebrations.",
    ingredients: [
      { name: "Basmati Rice", quantity: 2, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Mixed Vegetables (Carrot, Beans, Cauliflower, Peas)", quantity: 2, unit: "cups", isPantryStaple: false, category: "Vegetables" },
      { name: "Thick Curd (Dahi)", quantity: 0.75, unit: "cup", isPantryStaple: false, category: "Dairy" },
      { name: "Fried Onions (Birista)", quantity: 0.5, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Biryani Masala", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Mint & Coriander Leaves", quantity: 0.5, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Desi Ghee", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Saffron in warm milk", quantity: 3, unit: "tbsp", isPantryStaple: true, category: "Dairy" }
    ],
    instructions: [
      "Boil basmati rice with whole spices (cloves, cardamom, bay leaf) until 70% cooked; drain water.",
      "Marinate chopped vegetables with curd, biryani masala, ginger-garlic paste, mint, chilli powder, and salt for 15 minutes.",
      "Cook the marinated vegetables in a heavy-bottom pot until 80% tender.",
      "Layer half the parboiled rice over the vegetable masala. Top with fried onions, mint, and saffron milk.",
      "Add remaining rice, drizzle ghee, seal lid tightly with foil or dough, and cook on low heat (dum) for 15 minutes.",
      "Rest for 5 minutes before gently fluffing with a flat spoon. Serve with boondi raita."
    ]
  },
  {
    name: "Matar Mushroom Masala with Phulka",
    description: "Plump button mushrooms and sweet green peas simmered in a semi-dry spiced onion-tomato cashew gravy.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 10,
    cookTime: 18,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 310, protein: 14, carbs: 32, fat: 14, fiber: 6 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "healthy", "low-calorie"],
    imageUrl: "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=700&auto=format&fit=crop&q=80",
    tags: ["mushroom", "low calorie", "healthy dinner", "gourmet simple"],
    defaultDecisionTip: "Great low-calorie alternative to paneer with rich earthy mushroom umami flavor.",
    ingredients: [
      { name: "Button Mushrooms", quantity: 200, unit: "grams", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Peas (Matar)", quantity: 0.75, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Onion", quantity: 1, unit: "large", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato Puree", quantity: 0.75, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Ginger Garlic Paste", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Garam Masala", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Kasuri Methi", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Oil", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" }
    ],
    instructions: [
      "Wipe mushrooms clean, slice into halves or quarters. Sauté in 1 tsp oil on high flame for 2 mins; set aside.",
      "Heat remaining oil, add cumin seeds, minced onions, and sauté until golden.",
      "Add ginger-garlic paste and tomato puree; cook until oil separates.",
      "Add green peas, sautéed mushrooms, coriander powder, turmeric, and 1/2 cup water.",
      "Cover and simmer for 8 minutes until peas are tender and gravy is thick.",
      "Crush kasuri methi on top and serve hot with fresh rotis."
    ]
  },
  {
    name: "South Indian Sambar with Steamed Rice & Ghee",
    description: "Tangy toor dal stew loaded with drumsticks, pumpkin, and shallots simmered in homemade aromatic sambar masala and tamarind.",
    mealType: ["lunch", "dinner"],
    cuisine: "South Indian",
    prepTime: 15,
    cookTime: 20,
    difficulty: "Easy",
    servingSize: 3,
    nutrition: { calories: 370, protein: 15, carbs: 64, fat: 6, fiber: 10 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "high-protein", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1610192244261-3f33de3f55e4?w=700&auto=format&fit=crop&q=80",
    tags: ["south indian", "tangy", "protein rich", "comforting"],
    defaultDecisionTip: "Tangy tamarind & lentil broth packed with wholesome veggies and digestive spices.",
    ingredients: [
      { name: "Toor Dal", quantity: 1, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Shallots (Small Onions)", quantity: 10, unit: "pieces", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 1, unit: "large", isPantryStaple: false, category: "Vegetables" },
      { name: "Drumstick / Mixed Veggies", quantity: 1, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Sambar Powder", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Tamarind Pulp", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Mustard Seeds & Curry Leaves", quantity: 1, unit: "set", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Ghee / Coconut Oil", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Dairy" }
    ],
    instructions: [
      "Pressure cook toor dal with turmeric until mushy; whisk smooth.",
      "In a pot, boil shallots, drumsticks, and tomatoes with tamarind pulp, sambar powder, and salt until vegetables are soft.",
      "Pour cooked dal into the vegetable broth and bring to a rolling boil for 5 minutes.",
      "Prepare tadka in ghee with mustard seeds, fenugreek seeds, dry red chillies, curry leaves, and hing.",
      "Pour sizzing tadka into hot sambar and cover immediately to seal flavors.",
      "Serve over steamed rice with a generous spoonful of desi ghee."
    ]
  },
  {
    name: "Methi Thepla with Plain Curd & Mango Pickle",
    description: "Nutritious Gujarati flatbreads infused with fresh fenugreek leaves, gram flour, sesame seeds, and mild warming spices.",
    mealType: ["breakfast", "snack", "dinner"],
    cuisine: "Gujarati",
    prepTime: 10,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 320, protein: 10, carbs: 48, fat: 10, fiber: 7 },
    dietaryFlags: ["vegetarian", "quick-meal", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1505253758473-96b7015fcd40?w=700&auto=format&fit=crop&q=80",
    tags: ["travel friendly", "gut healthy", "iron rich", "easy breakfast"],
    defaultDecisionTip: "Stays fresh for days and provides a healthy burst of winter greens and fiber.",
    ingredients: [
      { name: "Fresh Methi (Fenugreek Leaves)", quantity: 1, unit: "cup chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Whole Wheat Flour", quantity: 1.5, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Besan (Gram Flour)", quantity: 0.25, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Sesame Seeds (Til)", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Curd (Yogurt)", quantity: 2, unit: "tbsp", isPantryStaple: false, category: "Dairy" },
      { name: "Turmeric & Chilli Powder", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" }
    ],
    instructions: [
      "Wash and finely chop fresh methi leaves.",
      "In a large bowl, mix wheat flour, besan, sesame seeds, spices, curd, 1 tbsp oil, and chopped methi.",
      "Knead into a soft pliable dough using minimal water.",
      "Divide into small balls and roll thin theplas.",
      "Roast on a hot tawa with a light brush of oil until golden brown spots appear on both sides.",
      "Serve warm or at room temperature with plain chilled curd and spicy pickle."
    ]
  },
  {
    name: "Classic Italian Pasta Aglio e Olio",
    description: "Al dente spaghetti tossed in golden garlic-infused extra virgin olive oil, fresh parsley, and spicy red pepper flakes.",
    mealType: ["dinner"],
    cuisine: "Continental",
    prepTime: 5,
    cookTime: 12,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 430, protein: 11, carbs: 62, fat: 16, fiber: 4 },
    dietaryFlags: ["vegetarian", "vegan", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1551183053-bf91a1d81141?w=700&auto=format&fit=crop&q=80",
    tags: ["quick gourmet", "minimalist", "date night", "under 15 mins"],
    defaultDecisionTip: "Fastest European comfort food with only 4 main ingredients from your pantry.",
    ingredients: [
      { name: "Spaghetti / Penne Pasta", quantity: 200, unit: "grams", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Extra Virgin Olive Oil", quantity: 3, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Garlic", quantity: 8, unit: "cloves thinly sliced", isPantryStaple: false, category: "Vegetables" },
      { name: "Chilli Flakes", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Fresh Parsley / Coriander", quantity: 3, unit: "tbsp chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Parmesan / Processed Cheese", quantity: 2, unit: "tbsp grated", isPantryStaple: false, category: "Dairy" }
    ],
    instructions: [
      "Boil pasta in well-salted water until al dente. Reserve 1/2 cup pasta cooking water before draining.",
      "In a wide skillet, heat olive oil over medium-low heat. Add thinly sliced garlic and fry slowly until golden and aromatic.",
      "Add chilli flakes and immediately remove from direct heat to prevent garlic from burning.",
      "Add drained pasta and 1/4 cup reserved pasta water into the garlic oil. Toss vigorously on medium heat until emulsion forms.",
      "Toss with finely chopped fresh parsley.",
      "Serve warm topped with freshly grated cheese and cracked black pepper."
    ]
  },
  {
    name: "Sprouts Chaat Bowl with Lemon & Sev",
    description: "Crunchy steamed mixed moong sprouts tossed with onions, tomatoes, cucumber, chaat masala, and fresh lemon juice.",
    mealType: ["snack", "breakfast"],
    cuisine: "North Indian",
    prepTime: 10,
    cookTime: 0,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 190, protein: 14, carbs: 30, fat: 2, fiber: 9 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "high-protein", "healthy", "low-calorie", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=700&auto=format&fit=crop&q=80",
    tags: ["super healthy", "zero oil", "weight loss", "protein punch"],
    defaultDecisionTip: "Zero oil, packed with 14g raw clean protein, and ready in 5 minutes.",
    ingredients: [
      { name: "Sprouted Moong Beans", quantity: 2, unit: "cups", isPantryStaple: false, category: "Grains & Pulses" },
      { name: "Onion", quantity: 1, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 1, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Cucumber", quantity: 0.5, unit: "cup diced", isPantryStaple: false, category: "Vegetables" },
      { name: "Chaat Masala", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Lemon", quantity: 1, unit: "piece", isPantryStaple: false, category: "Vegetables" },
      { name: "Fresh Mint & Coriander", quantity: 2, unit: "tbsp", isPantryStaple: false, category: "Vegetables" }
    ],
    instructions: [
      "Optionally steam sprouted moong for 3 minutes for easy digestion, or use raw for max crunch.",
      "In a large salad bowl, combine sprouts, chopped onions, tomatoes, and cucumber.",
      "Season with chaat masala, roasted cumin powder, black salt, and a pinch of red chilli powder.",
      "Squeeze fresh lemon juice generously and toss well.",
      "Garnish with chopped mint and coriander leaves. Enjoy immediately as an energizing snack."
    ]
  },
  {
    name: "Homestyle Chicken Curry with Steamed Rice",
    description: "Tender chicken pieces simmered in a fragrant onion, tomato, ginger, garlic, and whole spice Indian curry.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 15,
    cookTime: 25,
    difficulty: "Medium",
    servingSize: 3,
    nutrition: { calories: 510, protein: 36, carbs: 38, fat: 22, fiber: 4 },
    dietaryFlags: ["non-vegetarian", "high-protein", "gluten-free"],
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=700&auto=format&fit=crop&q=80",
    tags: ["high protein", "chicken", "comfort curry", "family favorite"],
    defaultDecisionTip: "Wholesome, rustic homemade chicken curry with 36g protein per portion.",
    ingredients: [
      { name: "Chicken (Curry Cut)", quantity: 500, unit: "grams", isPantryStaple: false, category: "Meat & Seafood" },
      { name: "Onion", quantity: 2, unit: "large sliced", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato Puree", quantity: 1, unit: "cup", isPantryStaple: false, category: "Vegetables" },
      { name: "Ginger Garlic Paste", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Chicken Masala / Garam Masala", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Mustard Oil / Ghee", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Coriander & Turmeric Powder", quantity: 1.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Rice", quantity: 1.5, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" }
    ],
    instructions: [
      "Marinate chicken with turmeric, half ginger-garlic paste, and salt for 15 minutes.",
      "Heat mustard oil in a heavy kadai, add whole spices (bay leaf, cloves, cardamom), and sliced onions.",
      "Fry onions until deep golden brown. Add remaining ginger-garlic paste and sauté.",
      "Add tomato puree and spice powders. Cook until oil separates.",
      "Add marinated chicken and bhuno (sear on high flame) for 6-8 minutes until sealed.",
      "Add 1.5 cups hot water, cover with lid, and simmer on low heat for 18-20 minutes until chicken is tender.",
      "Garnish with fresh coriander and serve with steamed rice or phulkas."
    ]
  },
  {
    name: "Classic Upma with Coconut Chutney",
    description: "Savory semolina porridge tempered with mustard seeds, curry leaves, ginger, green chillies, and roasted cashews.",
    mealType: ["breakfast", "snack"],
    cuisine: "South Indian",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 280, protein: 7, carbs: 48, fat: 7, fiber: 3 },
    dietaryFlags: ["vegetarian", "vegan", "quick-meal", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=700&auto=format&fit=crop&q=80",
    tags: ["quick breakfast", "south indian", "comforting"],
    defaultDecisionTip: "Light South Indian breakfast ready under 15 minutes using pantry rava.",
    ingredients: [
      { name: "Rava / Sooji (Semolina)", quantity: 1, unit: "cup", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Onion", quantity: 1, unit: "medium chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Mustard Seeds & Urad Dal", quantity: 1, unit: "tsp each", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Curry Leaves & Green Chilli", quantity: 1, unit: "set", isPantryStaple: false, category: "Vegetables" },
      { name: "Ginger", quantity: 1, unit: "tsp minced", isPantryStaple: false, category: "Vegetables" },
      { name: "Ghee / Oil", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Cashews", quantity: 8, unit: "pieces", isPantryStaple: true, category: "Grains & Pulses" }
    ],
    instructions: [
      "Dry roast rava in a pan on medium-low heat for 3-4 minutes until fragrant; set aside.",
      "Heat ghee/oil, fry cashews till golden; add mustard seeds, urad dal, curry leaves, ginger, and green chillies.",
      "Add chopped onions and sauté until soft.",
      "Pour in 2.5 cups of water, add salt, and bring to a rolling boil.",
      "Slowly stream in roasted rava with one hand while continuously whisking with the other to avoid lumps.",
      "Cover with lid and cook on lowest flame for 2-3 minutes. Drizzle a tsp of ghee on top and serve with chutney."
    ]
  },
  {
    name: "Baingan Bharta with Tawa Roti",
    description: "Smoky roasted eggplant mashed and cooked with garlic, onions, tomatoes, and aromatic Indian spices.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 15,
    cookTime: 15,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 290, protein: 7, carbs: 42, fat: 11, fiber: 10 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "healthy", "low-calorie"],
    imageUrl: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=700&auto=format&fit=crop&q=80",
    tags: ["smoky", "rustic", "fiber rich", "traditional"],
    defaultDecisionTip: "Rich smoky rustic flavor that delivers high dietary fiber with very few calories.",
    ingredients: [
      { name: "Large Eggplant (Bharta Baingan)", quantity: 1, unit: "large (400g)", isPantryStaple: false, category: "Vegetables" },
      { name: "Onion", quantity: 2, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 2, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Garlic", quantity: 6, unit: "cloves", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli", quantity: 2, unit: "pieces", isPantryStaple: false, category: "Vegetables" },
      { name: "Mustard Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" },
      { name: "Coriander & Cumin Powder", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" }
    ],
    instructions: [
      "Slit the eggplant, insert garlic cloves inside, brush with oil, and roast over open gas flame until charred and soft inside.",
      "Cool, peel off burnt skin, and mash the flesh with a fork.",
      "Heat mustard oil in a pan, add cumin seeds, chopped onions, and green chillies. Sauté till golden.",
      "Add chopped tomatoes, turmeric, chilli powder, and coriander powder; cook until soft.",
      "Add the mashed roasted eggplant and salt. Sauté on medium-high heat for 6-8 minutes to meld flavors.",
      "Garnish with lots of fresh coriander and serve with hot tawa rotis."
    ]
  },
  {
    name: "Classic Vegetable Pulao with Mint Raita",
    description: "One-pot fragrant long-grain basmati rice cooked with whole spices, green peas, carrots, and potatoes.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 10,
    cookTime: 15,
    difficulty: "Easy",
    servingSize: 3,
    nutrition: { calories: 380, protein: 8, carbs: 68, fat: 8, fiber: 6 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "quick-meal", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=700&auto=format&fit=crop&q=80",
    tags: ["one pot", "easy meal", "lunchbox favorite", "quick dinner"],
    defaultDecisionTip: "Fastest 20-minute one-pot meal that requires minimal dishes and cooks in one cooker.",
    ingredients: [
      { name: "Basmati Rice", quantity: 1.5, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Mixed Veggies (Peas, Carrots, Beans, Potato)", quantity: 1.5, unit: "cups", isPantryStaple: false, category: "Vegetables" },
      { name: "Onion", quantity: 1, unit: "sliced", isPantryStaple: false, category: "Vegetables" },
      { name: "Whole Spices (Cumin, Cloves, Cardamom, Bay leaf)", quantity: 1, unit: "set", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Ghee / Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Ginger Garlic Paste", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" }
    ],
    instructions: [
      "Wash basmati rice and soak in water for 15 minutes.",
      "In a pressure cooker, heat ghee, add whole spices and sliced onions; fry until lightly golden.",
      "Add ginger-garlic paste and chopped mixed vegetables; sauté for 2 minutes.",
      "Add drained rice, 2.5 cups water, and salt. Gently mix.",
      "Close lid and pressure cook on medium flame for 2 whistles.",
      "Allow pressure to release naturally, fluff gently with a fork, and serve with boondi or cucumber raita."
    ]
  },
  {
    name: "Stuffed Aloo Paratha with Fresh Curd & Butter",
    description: "Crisp golden whole wheat flatbreads stuffed with spiced mashed potatoes, ginger, green chillies, and amchur.",
    mealType: ["breakfast", "lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 15,
    cookTime: 15,
    difficulty: "Medium",
    servingSize: 2,
    nutrition: { calories: 420, protein: 9, carbs: 65, fat: 14, fiber: 7 },
    dietaryFlags: ["vegetarian"],
    imageUrl: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=700&auto=format&fit=crop&q=80",
    tags: ["punjabi breakfast", "comfort", "filling"],
    defaultDecisionTip: "Comforting classic Punjabi paratha that keeps you energized and full for hours.",
    ingredients: [
      { name: "Whole Wheat Flour (Atta)", quantity: 2, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Potato", quantity: 3, unit: "boiled & mashed", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli & Ginger", quantity: 1, unit: "tbsp minced", isPantryStaple: false, category: "Vegetables" },
      { name: "Amchur (Dry Mango Powder)", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Ajwain & Kasuri Methi", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Butter / Desi Ghee", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Dairy" }
    ],
    instructions: [
      "Mix boiled mashed potatoes with chopped chillies, ginger, amchur, ajwain, coriander, and salt.",
      "Knead wheat flour into a soft pliable dough.",
      "Roll a small dough circle, place potato ball in center, seal edges into a dumpling, and gently roll flat without tearing.",
      "Roast on a hot tawa with generous ghee/butter until crisp and deeply golden with brown spots.",
      "Serve hot with fresh cold curd, pickle, and a cube of white butter melting on top."
    ]
  },
  {
    name: "Crispy Onion Uttapam with Chutney",
    description: "Thick savory South Indian fermented rice pancake topped with caramelized shallots, green chillies, and curry leaves.",
    mealType: ["breakfast", "dinner"],
    cuisine: "South Indian",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 310, protein: 8, carbs: 54, fat: 8, fiber: 5 },
    dietaryFlags: ["vegetarian", "vegan", "gluten-free", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=700&auto=format&fit=crop&q=80",
    tags: ["south indian", "quick dinner", "fluffy pancake"],
    defaultDecisionTip: "Fast, fluffy savory pancake that turns dosa batter into a thick, satisfying meal in 10 mins.",
    ingredients: [
      { name: "Dosa/Idli Batter", quantity: 2, unit: "cups", isPantryStaple: false, category: "Grains & Pulses" },
      { name: "Onion", quantity: 2, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 1, unit: "finely chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Green Chilli", quantity: 2, unit: "minced", isPantryStaple: false, category: "Vegetables" },
      { name: "Curry Leaves", quantity: 6, unit: "leaves chopped", isPantryStaple: false, category: "Vegetables" },
      { name: "Oil / Ghee", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Dairy" }
    ],
    instructions: [
      "Heat a tawa, pour a ladle of thick batter and spread gently into a thick disc.",
      "Generously press chopped onions, tomatoes, green chillies, and curry leaves into the wet surface.",
      "Drizzle oil around edges, cover with a lid, and cook on medium flame for 2-3 minutes until golden crisp bottom forms.",
      "Flip carefully and cook the topping side for 1-2 minutes until onions get sweet caramelization.",
      "Serve steaming hot with tomato-onion chutney or coconut chutney."
    ]
  },
  {
    name: "Amritsari Chole with Bhature / Steamed Rice",
    description: "Dark, robust chickpea curry slow-simmered with black tea, anardana, and freshly pounded Amritsari chole masala.",
    mealType: ["lunch", "dinner"],
    cuisine: "North Indian",
    prepTime: 15,
    cookTime: 30,
    difficulty: "Medium",
    servingSize: 4,
    nutrition: { calories: 470, protein: 18, carbs: 74, fat: 12, fiber: 14 },
    dietaryFlags: ["vegetarian", "vegan", "high-protein", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=700&auto=format&fit=crop&q=80",
    tags: ["punjabi classic", "high fiber", "protein rich", "weekend lunch"],
    defaultDecisionTip: "Flavorful Punjabi chickpea curry loaded with 18g plant protein and deep warm spice notes.",
    ingredients: [
      { name: "Kabuli Chana (Chickpeas)", quantity: 2, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Onion", quantity: 2, unit: "medium", isPantryStaple: false, category: "Vegetables" },
      { name: "Tomato", quantity: 2, unit: "pureed", isPantryStaple: false, category: "Vegetables" },
      { name: "Chole Masala", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Tea Bag (for dark color)", quantity: 1, unit: "bag", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Ginger Garlic Paste", quantity: 1.5, unit: "tbsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Ghee / Mustard Oil", quantity: 2, unit: "tbsp", isPantryStaple: true, category: "Oils & Sauces" }
    ],
    instructions: [
      "Soak chickpeas overnight. Pressure cook with 1 tea bag, whole spices, and salt for 5-6 whistles until soft.",
      "Discard tea bag.",
      "Heat ghee in a pan, fry finely chopped onions until dark brown; add ginger-garlic paste and tomato puree.",
      "Add chole masala, amchur powder, kasuri methi, and salt. Cook until oil surfaces.",
      "Add boiled chana with its dark broth; mash a few chickpeas to thicken gravy.",
      "Simmer for 15 minutes on low flame. Temper with ginger juliennes and green chillies in hot ghee."
    ]
  },
  {
    name: "Crispy Corn & Capsicum Chaat",
    description: "Golden sweet corn kernels tossed with crunchy bell peppers, onions, chaat masala, butter, and lime.",
    mealType: ["snack"],
    cuisine: "North Indian",
    prepTime: 5,
    cookTime: 5,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 210, protein: 5, carbs: 36, fat: 6, fiber: 5 },
    dietaryFlags: ["vegetarian", "gluten-free", "quick-meal", "healthy"],
    imageUrl: "https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=700&auto=format&fit=crop&q=80",
    tags: ["quick snack", "kids snack", "tea time", "under 10 mins"],
    defaultDecisionTip: "Instant 10-minute tea-time snack loved by kids and adults alike.",
    ingredients: [
      { name: "Sweet Corn Kernels", quantity: 2, unit: "cups", isPantryStaple: false, category: "Vegetables" },
      { name: "Capsicum", quantity: 0.5, unit: "diced", isPantryStaple: false, category: "Vegetables" },
      { name: "Butter", quantity: 1, unit: "tbsp", isPantryStaple: true, category: "Dairy" },
      { name: "Chaat Masala", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Lemon Juice", quantity: 1, unit: "tbsp", isPantryStaple: false, category: "Vegetables" },
      { name: "Black Pepper", quantity: 0.5, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" }
    ],
    instructions: [
      "Boil sweet corn in salted water for 3-4 minutes and drain.",
      "Melt butter in a skillet, add boiled corn and diced capsicum.",
      "Sauté on high flame for 2 minutes to get a slight smoky char.",
      "Transfer to a bowl, toss with chaat masala, black pepper, and fresh lemon juice.",
      "Serve warm in snack cups."
    ]
  },
  {
    name: "Curd Rice with Tadka (Thayir Sadam)",
    description: "Cooling tempered South Indian yogurt rice seasoned with mustard seeds, ginger, curry leaves, green chillies, and pomegranate.",
    mealType: ["lunch", "dinner"],
    cuisine: "South Indian",
    prepTime: 5,
    cookTime: 10,
    difficulty: "Easy",
    servingSize: 2,
    nutrition: { calories: 290, protein: 9, carbs: 46, fat: 8, fiber: 2 },
    dietaryFlags: ["vegetarian", "gluten-free", "healthy", "quick-meal"],
    imageUrl: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=700&auto=format&fit=crop&q=80",
    tags: ["cooling", "gut healthy", "probiotic", "summer special"],
    defaultDecisionTip: "Naturally rich in gut-friendly probiotics; soothing and refreshing in hot weather.",
    ingredients: [
      { name: "Soft Cooked Rice", quantity: 1.5, unit: "cups", isPantryStaple: true, category: "Grains & Pulses" },
      { name: "Fresh Curd (Dahi)", quantity: 1, unit: "cup", isPantryStaple: false, category: "Dairy" },
      { name: "Milk", quantity: 0.25, unit: "cup", isPantryStaple: false, category: "Dairy" },
      { name: "Mustard Seeds & Urad Dal", quantity: 1, unit: "tsp", isPantryStaple: true, category: "Spices & Condiments" },
      { name: "Curry Leaves & Green Chilli", quantity: 1, unit: "set", isPantryStaple: false, category: "Vegetables" },
      { name: "Grated Ginger", quantity: 1, unit: "tsp", isPantryStaple: false, category: "Vegetables" },
      { name: "Pomegranate Seeds", quantity: 2, unit: "tbsp", isPantryStaple: false, category: "Vegetables" }
    ],
    instructions: [
      "Mash soft cooked warm rice gently with a spoon. Allow to cool slightly.",
      "Mix in fresh curd, a splash of milk (keeps it fresh and non-sour), and salt.",
      "Heat 1 tbsp oil in a small tadka pan, crackle mustard seeds, urad dal, ginger, green chillies, and curry leaves.",
      "Pour tadka over curd rice and mix well.",
      "Top with crunchy pomegranate seeds and serve chilled with lime pickle."
    ]
  }
];
